CREATE TABLE custom (
  id BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  create_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (id)
) ENGINE=InnoDB;
